# Optionally override the fully qualified name
fullnameOverride: "keycloak"

image:
  # The Keycloak image repository
  repository: quay.io/keycloak/keycloak
  # Overrides the Keycloak image tag whose default is the chart appVersion
  tag: "17.0.1-legacy"

# Pod resource requests and limits
resources: {}
  # requests:
  #   cpu: "500m"
  #   memory: "1024Mi"
  # limits:
  #   cpu: "500m"
  #   memory: "1024Mi"

contextPath: identity/connect/auth

# Liveness probe configuration
livenessProbe: |
  httpGet:
    path: /identity/connect/auth/
    port: http
  initialDelaySeconds: 0
  timeoutSeconds: 5

# Readiness probe configuration
readinessProbe: |
  httpGet:
    path: /identity/connect/auth/realms/master
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 1

# Startup probe configuration
startupProbe: |
  httpGet:
    path: /identity/connect/auth/
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 1
  failureThreshold: 60
  periodSeconds: 5  

extraEnv: |
  - name: KC_HOSTNAME_PATH
    value: /identity/connect 
  - name: KC_HTTP_RELATIVE_PATH
    value: /identity/connect 

pgchecker:
  image:
    # Docker image used to check Postgresql readiness at startup
    repository: docker.io/busybox
    # Image tag for the pgchecker image
    tag: 1.32
  
postgresql:
  ## @param fullnameOverride String to fully override common.names.fullname template
  fullnameOverride: keycloak-postgresql
  
  global:
    storageClass: "nfs-retain-app"

  ## Init containers parameters:
  ## volumePermissions: Change the owner of the persist volume mountpoint to RunAsUser:fsGroup
  ##
  volumePermissions:
    ## @param volumePermissions.enabled Enable init container that changes volume permissions in the data directory (for cases where the default k8s `runAsUser` and `fsUser` values do not work)
    ##
    enabled: true    
