# Optionally override the fully qualified name
fullnameOverride: "keycloak"

image:
  # The Keycloak image repository
  repository: quay.io/keycloak/keycloak
  # Overrides the Keycloak image tag whose default is the chart appVersion
  tag: "17.0.1-legacy"

# Pod resource requests and limits
resources: {}
  # requests:
  #   cpu: "500m"
  #   memory: "1024Mi"
  # limits:
  #   cpu: "500m"
  #   memory: "1024Mi"

extraEnv: |
  - name: KEYCLOAK_USER
    value: keycloak
  - name: KEYCLOAK_PASSWORD
    value: keycloak
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: false
  - name: KC_LOG_LEVEL
    value: debug

pgchecker:
  image:
    # Docker image used to check Postgresql readiness at startup
    repository: docker.io/busybox
    # Image tag for the pgchecker image
    tag: 1.32
  
postgresql:
  ## @param fullnameOverride String to fully override common.names.fullname template
  fullnameOverride: keycloak-postgresql
  
  global:
    storageClass: "nfs-retain-app"
    postgresql:
      postgresqlPostgresPassword: keycloak

  ## Init containers parameters:
  ## volumePermissions: Change the owner of the persist volume mountpoint to RunAsUser:fsGroup
  ##
  volumePermissions:
    ## @param volumePermissions.enabled Enable init container that changes volume permissions in the data directory (for cases where the default k8s `runAsUser` and `fsUser` values do not work)
    ##
    enabled: true    
