apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /identity/connect(/|$)(.*)
        pathType: Prefix
        backend: 
          service: 
            name: "{{ include "keycloak.fullname" . }}-http"
            port:
              number: {{ .Values.service.httpPort }}
