apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.opensearch-dashboards.fullnameOverride | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri:
        prefix: /opensearch
    route:
    - destination:
        host: "{{ .Values.opensearch-dashboards.fullnameOverride | trunc 63 | trimSuffix "-" }}"
        port:
          number: {{ .Values.opensearch-dashboards.service.port }}
