apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.dashboards.fullnameOverride }}"
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri:
        prefix: /opensearch
    route:
    - destination:
        host: "{{ .Values.dashboards.fullnameOverride }}"
        port:
          number: {{ .Values.dashboards.service.port }}
